### ISSUE TITLE
no test.ts, karma.conf.js file

### ISSUE THREAD

**Issue by yangwulong1978** [PacktPublishing/Mastering-Angular-Test-Driven-Development#13]
in your Chapter 1, you mentioned, there are some test.ts, karma.conf.js file.  I searched in your code example,for Chapter 1, chapter2, there are no that files.
and I followed your guid to create new angular 18 project, there are also no these files.
please advise where are the files, or how to generate them.

**Comment by amilamen** [comment]
Hi @yangwulong1978 ,
I hope you're doing well!

Thank you for your issue.
You're right.

It's an omission on my part.
In new versions of Angular, the two files don't exist and you have to create them manually.

In fact, Karma configurations are already an integral part of the core of an Angular project.

When you need to make custom configurations, you need to create these two files and make a configuration in the angular.json file.

Thank you very much for your feedback.
I'll fix it.

However, it's not a problem for the rest of the project.

**Comment by amilamen** [comment]
Hi @yangwulong1978 ,
I hope doing well!

You can read the [ReadMe](https://github.com/PacktPublishing/Mastering-Angular-Test-Driven-Development/blob/main/README.md) file of repo about your issue.

Take care,
Best regards,
